### ISSUE TITLE
Update upstream Appbundler repo now that it has moved to GitHub

### ISSUE THREAD

**Issue by joewiz** [evolvedbinary/appbundler-maven-plugin#1]
See https://github.com/evolvedbinary/appbundler-maven-build/issues/4.

**Comment by adamretter** [comment]
I have published version 1.0.2 to Maven Central with the updated AppBundler.

**Comment by joewiz** [comment]
Cool. I'm curious, since [my patch](https://github.com/evolvedbinary/appbundler-maven-build/pull/1/files#diff-d27f4fb38062206ac79cb6ac667c4e7a) is still part of the `appbundler-maven-build` repo ([my PR reverting it](https://github.com/evolvedbinary/appbundler-maven-build/pull/3) hasn't been merged yet), did the build still work? I imagined that the patch portion of the build might fail.

**Comment by adamretter** [comment]
@joewiz I removed your patch in https://github.com/evolvedbinary/appbundler-maven-build/commit/b2bf440df66b007e76dce367405337a5b449c124
